yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/'
                                   'password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/'
                                       'password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/'
                                  'password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/'
                                      'password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uid64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/'
                                         'password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/'
                                          'password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

from .models import Group, Post, User


@login_required
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    all_authors_posts = Post.objects.select_related('author').all()
    post_count = 0
    for post in all_authors_posts:
        if post.author.username == username:
            post_count += 1
    post_list = Post.objects.filter(author=author)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_count': post_count,
        'author': author
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    all_authors_posts = Post.objects.select_related('author').all()
    post_count = 0
    for post in all_authors_posts:
        if post.id == post_id:
            author_of_post = post.author.username
    for post in all_authors_posts:
        if post.author.username == author_of_post:
            post_count += 1
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post_count': post_count,
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор этого проекта</h1>
<h3>
  Меня зовут Кремнёв Андрей, и я начинающий бэкендер :)
</h3>
<p>
  Когда достигну каких-нибудь значимых (для себя) результатов 
  - обязательно дополню эту страничку. Пока что мне немножечко 
  лень этим заниматься, но ИНОГДА можно себе такое позволить. 
  А пока могу лишь сказать, что вдохновляет на будущие 
  свершения наша змея Ева, и она, как это ни странно - 
  ПИТОН. Настоящий ковровый питон, целых 3 года от роду. 
  Правда. Давайте договоримся: доползу до половины 
  курса Python-разработчик от Яндекс.Практикума - 
  обязательно прикреплю фото, хорошо?
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>В проекте используется Python 3.10 с фреймворком 
        Django 2.2.9
    </p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->      
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        ...
      {% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% if not post_detail %}
      <div class="container py-5">  
      {% endif %}
      {% block content %}
          Контент не подвезли :(
        {% endblock %}
      {% if not post_detail %}
      </div>
      {% endif %}
         
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
          width="30" height="30"
          class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}<p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %} 
{% block content %}   
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
    </article>
    {% if post.group %}
      <a href="{%url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
 Пост {{ post.text|truncatechars:30 }}
{% endblock %} 
{% block content %}    
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
        <li class="list-group-item">
          Группа: {{ group.title }}
          <a href="{%url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span > {{ post_count }} </span>
      </li>
      <li class="list-group-item">
        <a href="{%url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      {{ post.text }}
    </p>
  </article>
</div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %} 
{% block content %}    
<h1>Все посты пользователя {{ author.get_full_name }} </h1>
<h3>Всего постов: {{ post_count }} </h3>
{% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
          <a href="{%url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      {{ post.text }}
    </p>
     <a href="{%url 'posts:post_detail' post.pk %}">подробная информация </a>
  </article>       
  {% if post.group %}
    <a href="{%url 'posts:group_list' post.group.slug %}">
      все записи группы
    </a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Войти
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}
  Пароль изменён
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Пароль изменён
      </div>
      <div class="card-body"> 
        <p>Пароль изменён успешно</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}
  Изменение пароля
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Изменить пароль
      </div>
      <div class="card-body">
        {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Восстановление пароля завершено
      </div>
      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="{% url 'users:login' %}">войти</a>
      </div> 
    </div> 
  </div>
</div>  
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
  Новый пароль
{% endblock %}
{% block content %}
{% load user_filters %}
{% if validlink %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Введите новый пароль
      </div>
      <div class="card-body">
        {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
    
              <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
              >
              {% csrf_token %}
    
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Назначить новый пароль
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Ошибка
      </div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}
{% endblock %}
        

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Отправлено письмо
      </div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
      </div> 
    </div> 
  </div>
</div>
{% endblock %}
        

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля
{% endblock %} 
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
          <div class="card-body">
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
    
              <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
              >
              {% csrf_token %}
    
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 